### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by Uptaker** [open-eid/linux-installer#113]
Hello!

I see that Ubuntu and other Debian based distros appear to be the only officially supported ones. Is there perhaps a possibility to create a Flatpak package?

- It would support all distributions
- It would lead to zero dependency issues (not affecting the user's system or repositores)
- It's installable with a click of a button (eg. useful for beginners)

There are other options as well, such as AppImage, but it seems like Flatpak applications are most widespread by quite a large margin and would be fit for a wider userbase. Meanwhile Snaps are only pushed by Ubuntu and use a proprietery backend.

Seems like a good use case for such critical software. Thoughts?

**Comment by metsma** [comment]
See https://github.com/open-eid/DigiDoc4-Client/issues/969.

**Comment by web-pat** [comment]
As mentioned in the issue referenced above, a flatpak has recently been released on [Flathub](https://flathub.org/apps/ee.ria.qdigidoc4).
