### ISSUE TITLE
Support for Zorin and other Ubuntu Based Distros

### ISSUE THREAD

**Issue by FKrauss** [open-eid/linux-installer#116]
Hi there,

I tinkered a bit with the install sh script and made it work in Zorin. I found it weird that Neon is supported there but not Zorin. 

Most of these Ubuntu based systems are the exact same thing under the hood except for the default desktop envrionment. The vast majority of them should work out of the box. Although I do understand that the maintainers might not want to claim that a certain OS is supported since it can be binding.

I'm gonna send a PR for it, if you want, merge it and Zorin would be supported.

I tested and it is working fine, using the drivers to read the card reader and doing all functions.

Even if this does not get merged it serves for anyone who wants to do it at their own risk. I wrote a brief post on how I did it [here](https://bright-husky.pikapod.net/estonian-e-id-on-zorin/?utm_source=github) and even non developers that use Linux can follow.

**Comment by kristelmerilain** [comment]
Hello!

Thank you for the contrubution. Pull request is merged.

**Comment by FKrauss** [comment]
You're welcome! do we need to tell someone to add it to the website? 
[Here](https://www.id.ee/en/article/operating-systems-supported-by-id-software/?ref=bright-husky.pikapod.net)

**Comment by kristelmerilain** [comment]
We only list supported and tested operating systems in the id.ee website.
