### ISSUE TITLE
Contribution for fedora and related distributions

### ISSUE THREAD

**Issue by step21** [open-eid/linux-installer#18]
I would like to contribute packaging information along with instructions on how to keep this current and keep it in fedora repositories or generate separate rpm packages, in case this should ever be necessary such as if the current maintainer drops.
Now the questions - would it be appropriate to add this here or is it preferable to add this to each package such as qesteidutil which also has a '/debian' folder for example or should this be in a new repo, as I saw that there are at least some repos per distribution such as one for gentoo and the one for ubuntu/debian.

**Comment by metsma** [comment]
Doesn't fedora have own repo?
http://pkgs.fedoraproject.org/cgit/rpms/qesteidutil.git/
we can add needed references to wiki or to source readmes.

**Comment by step21** [comment]
Yes, they do, as do debian and ubuntu normally. But the idea was to add at least an instruction and spec file (along with a link to fedora) also here, so that in case someone looks here (rpm is not only used by fedora) or there is no maintainer anymore, there is easy access to a doc that describes how to packages and how to distribute the package if desirable.

**Comment by metsma** [comment]
Feel free to create pull requests to components or create wiki pages
