### ISSUE TITLE
Doesn't actually work on wily

### ISSUE THREAD

**Issue by atleta** [open-eid/linux-installer#2]
Hi,

Even though the install script will add the vivid (15.04) repo if run on wily (15.10), the packages themselves are not installable due to missing/broken dependencies. What I found is that the vivid package of estonianidcard depends (transitively) on libxml-security-c17 (through libdigidocpp-tools), but in wily it's called libxml-security-c17v5 .

To fix this, you shoud add the latter as an optional dependency in libdigidocpp-tools .

Also, it would be nice if (probably in this repo) you'd have a make script that would clone and build all the components that are needed on linux.

**Comment by martinpaljak** [comment]
Yes. If you want to provide one before we get to it, please do :)

**Comment by atleta** [comment]
Sure, will look into it as soon as I have some time (also building the packages on Wily & fixing the control files).

Köszönöm :)

**Comment by aesedepece** [comment]
I have tried the following to partially install on Wily.

Make sure I don't have ``libxml-security-c17v5`` installed in my system:
```bash
sudo apt-get remove libxml-security-c17v5
```
Then download the old ``libxml-security-c17`` from PPA:
http://launchpadlibrarian.net/173904107/libxml-security-c17_1.7.2-3_amd64.deb

Install it and then run the ``install-open-eid.sh`` installation script.

ID-card utility and DigiDoc3 client open and can see the ID, but any operation needing PIN fails.

**Comment by aesedepece** [comment]
EDIT: The aforementioned process works like a charm. It was just that my certificates were not enabled yet by the time I tried.

**Comment by metsma** [comment]
New official release is available at https://installer.id.ee and wily is supported
