### ISSUE TITLE
Ubuntu 18.04 support

### ISSUE THREAD

**Issue by 2tunnels** [open-eid/linux-installer#21]
When are you planning to add Ubuntu 18.04 support?

**Comment by aldas** [comment]
Bump! 17.10 Artful Aardvark will have its EOL date july 2018.

**Comment by aldas** [comment]
so I wrote to tech support and asked when it will happen - answer is:

> Ubuntu 18.04 versiooni tugi on oodatud id-tarkvara järgimise uuendusega, mis meie andmete järgi peaks toimuma suvi/sügis 2018. Kahjuks, rohkem infot uuendamise kohta hetkel pole.

but from RIA blog I found answer

https://blog.ria.ee/linux/#comment-9174
> Ubuntu 18.04 LTS tugi tuleb tarkvara uue reliisiga, mis on planeeritud juuni keskpaika.


so maybe in 2-3 weeks we will have next release with 18.04 support if not then this summer/autumn.

**Comment by amaccuish** [comment]
Thanks @aldas ! I just emailed them too and then saw your message.

**Comment by rinu** [comment]
Ubuntu 18.04 is now listed as supported on id.ee. I could successfully install the software and log in to my bank. Which is awesome, I can finally get things done on my work computer.

But there are several minor issues:
- Sometimes (especially the first time) the card must be in the reader while the browser is (re)started. Inserting the card while the browser is running doesn't work. This is true for both chrome and firefox.
- 32-bit support seems to be dropped so `/etc/apt/sources.list.d/ria-repository.list` should include `[arch=amd64]` to avoid an error during `apt update`
- App launchers seem to be missing. When searching for "id" I only got "TeRa Client". I also accidentally found the `qdigidoc4` executable which seems much more useful.
- When `qdigidoc4` first ran it failed to read any personal details from the card. Can not reproduce.

**Comment by AlexDaniel** [comment]
FWIW bionic packages work more or less ok on debian unstable. I can indeed log in to websites in firefox, but qesteidutil segfaults trying to get data from the card.

**Comment by amaccuish** [comment]
@AlexDaniel I also have the segfault problem. Should I create a new issue and upload the dump?

**Comment by AlexDaniel** [comment]
@amaccuish yes, please.

**Comment by kristelmerilain** [comment]
@rinu 
„Sometimes (especially the first time) the card must be in the reader while the browser is (re)started. Inserting the card while the browser is running doesn't work. This is true for both chrome and firefox.“
If you install new ID software you need to restart your browser. Unfortunately we could not reproduce it, Chrome readed ID-card even if it was inserted into reader after the program was launched. 

„32-bit support seems to be dropped so /etc/apt/sources.list.d/ria-repository.list should include [arch=amd64] to avoid an error during apt Update“
„Desktop app is hard to find. When searching for "id" or "id card" I only got "TeRa Client". I later accidentally found the qdigidoc4 executable which seems much more useful. I did not think to search for "digidoc" initially.“
We gave this information to our developers and hope to resolve these issues in next release.
Thank you for the suggestions.

**Comment by amaccuish** [comment]
opened #26 in relation to crashing
