### ISSUE TITLE
ID Card Utility crash on Ubuntu 18.04

### ISSUE THREAD

**Issue by amaccuish** [open-eid/linux-installer#26]
Attached dump.

[dump.txt](https://github.com/open-eid/linux-installer/files/2111295/dump.txt)

**Comment by metsma** [comment]
please can you install debug symbols and attach backtrace also

**Comment by metsma** [comment]
Also can you create report to correct module
(https://github.com/open-eid/org/wiki)

**Comment by amaccuish** [comment]
Sure I'll open one up on https://github.com/open-eid/qesteidutil/, but debug symbols for what? OpenSC, a particular library?

**Comment by metsma** [comment]
Continued int qesteidutil module open-eid/qesteidutil#104
