### ISSUE TITLE
Please add support for Debian Jessie

### ISSUE THREAD

**Issue by MagicFab** [open-eid/linux-installer#3]
Debian Jessie (8) [was released in April 2015](https://wiki.debian.org/DebianReleases) and is the current stable release. Expected EOL is June 2018. 

Thank you for considering adding support for it in the installer.

**Comment by metsma** [comment]
Can you test which ubuntu packages are working on Jessie

**Comment by MagicFab** [comment]
I successfully had installed those available in January, haven't tried since then.

**Comment by fisher** [comment]
+1 for Debian. As of Jul 2017 the stable branch is Debian 9.0 "stretch", https://wiki.debian.org/LTS

And the installation script still looking for outdated Wheezy.

**Comment by AlexDaniel** [comment]
I think if you're on jessie you can manage to install it, but it's not installable on anything beyond that (with the provided installation script or not). So, on jessie, there is a problem with [``qesteidutil``](https://installer.id.ee/media/ubuntu/dists/artful/main/binary-amd64/Packages) package:

<code>
Depends: fonts-liberation, pcscd (>= 1.5), libc6 (>= 2.14), libgcc1 (>= 1:3.0), libpcsclite1 (>= 1.3.0), libqt5core5a (>= 5.7.0), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5network5 (>= 5.0.2), libqt5widgets5 (>= 5.0.2), <b>libssl1.0.0 (>= 1.0.2~beta3)</b>, libstdc++6 (>= 6)
</code>

There is no 1.0.2 version of [libssl1.0.0](https://packages.qa.debian.org/o/openssl.html) package in normal debian repos. If you're on jessie, then perhaps it is installable if you add `jessie-backports` repository. That should work, I think I had it installed on jessie eventually.

However, on other versions of debian (even when using `artful` packages) it seems to be broken beyond repair:
```
opensc : Depends: libreadline6 (>= 6.0) but it is not installable
```

`libreadline6` is not a thing anymore in debian.


How come there is no proper support for debian when it comes to such an essential package? And while we are at it, why can't we have it included in debian repos? What's blocking it?

**Comment by teadur** [comment]
You can use the debian jessie backports version of openssl on Stretch.
But actualy its now impossible to use id card on debian jessie, becaue RIA decided to drop support for ubuntu trusty packages, so basicaly only Debian you can use id card is Stretch with debian jessie backported openssl (what a mess).

I talked to RIA support about why the decided to drop trusty packages and their response was that so few people are using ubuntu trusty ( and debian wheezy/jessie) that they decided to drop the support in favor of Ubuntu 17.x because its so big effort to keep supporting old releases ( i dont know how that makes any sense when the software releases are really stable on older linuxes, how it could be big effort remains mystery to me)

**Comment by AlexDaniel** [comment]
Eh, that's unacceptable. If RIA themselves are doing such a piss-poor job, who'd be the right person to contact if we want to get things moving into the right direction?

**Comment by metsma** [comment]
There is always possible to create own packages and repos. Like other distros are doing Gentoo, SuSe, Mandriva, Fedroa and Slack

**Comment by AlexDaniel** [comment]
@metsma what do you even mean? 😕 Are you saying that users are supposed to share .deb packages with each other for security related software?

**Comment by metsma** [comment]
Or you can become maintainer and push packages to upstream

**Comment by teadur** [comment]
If i would be good at debian packaging i would surely do it, but sadly i'm not.
I think the most sane solution would be to get RIA re-support trusty but i dont see that happening.

I dont think its trivial to become debian maintainer and get the packages to upstream and even if its done they packages would show up at buster not stretch or any of the releases mentioned here.

Cleanest solution would be that RIA does the packages right, sadly if they havent package for Debian last 10 years i dont see that happenig, second best would be that they bring back trusty support then we can workaround the issue and fix the installer.

**Comment by MagicFab** [comment]
Debian Jessie is now "old-stable". I'll open a new ticket requesting support for Debian and explain why it's important (and more viable).

**Comment by AlexDaniel** [comment]
@metsma 

> Or you can become maintainer and push packages to upstream

Please see #42.

**Comment by metsma** [comment]
> @metsma
> 
> > Or you can become maintainer and push packages to upstream
> 
> Please see #42.

This out of context comment and applies only for IDEMIA driver packages.
As as stated before, feel free to become debian maintainer and publish packages to debian.
Debian is community maintained distribution and you have all tools and code available to contribute packages to debian.
Debian policy also states that submitter cannot be company or organization which RIA is.

**Comment by MagicFab** [comment]
@metsma @AlexDaniel please discuss in #16 - this issue is not current and it's closed. #16 refers to proper support in Debian Stable.

**Comment by fisher** [comment]
> Debian policy also states that submitter cannot be company or organization which RIA is.

Fuck RIA.

(It's not you, it's the company of yours).
