### ISSUE TITLE
Upgrade needs manual removing and reinstalling.

### ISSUE THREAD

**Issue by adojaan** [open-eid/linux-installer#4]
Please try to detect pre-existing installation of older version and include removing of it, if it is not possible to  upgrade reliably. Installing with this .sh script succeeds without errors but the versions are not actually upgraded. 
Ubuntu 16.10. After running .sh script the metapackage version was 17.01.1686-1610.  Qesteidutil still showed Version: 3.12.2.1206-1510 and qdigidoc Version: 3.12.1.1450-1510. For id.ee helpdesk it seemed to be well-known problem, they instructed to remove the software sudo apt-get remove qesteidutil opensc and reinstall with .sh script. 
Now it works fine and versions are new: 
Package: qesteidutil Version: 3.12.4.1226-1604
Package: qdigidoc Version: 3.12.6.1481-1610

**Comment by cgfrost** [comment]
I also have this problem, exactly as described on Ubuntu 16.10.

**Comment by karltalum2e** [comment]
Updating eid-software is done together with updating all the system packages. Therefore please try to use "sudo apt-get update && upgrade" to get the latest version of eid-software.

The script is only made for initial installment and not for updating the software.

**Comment by cgfrost** [comment]
Everything is working again, thank you so much.
