### ISSUE TITLE
No source code to port to Debian / licensing issues

### ISSUE THREAD

**Issue by martinpaljak** [open-eid/linux-installer#42]
Relates to #16. Latest open-eid package brings in badly licensed (No license information in packages, usage of OpenSSL without attribution, #36 #37 #41  etc) awp package, which does not work supported platforms and also not on Debian 8/9 and has no source code to port or fix either. This is a serious regression.

**Comment by plaes** [comment]
Having source code would also might make it possible to support architectures other than x86 and amd64.

**Comment by thodt-md** [comment]
Any plans to ~reverse engineer this monstrosity~ make a clean-room middleware implementation based on the published specs? :smiling_imp:

**Comment by martinpaljak** [comment]
Unlike 15 years ago, a _lot_ of taxpayer money has been poured into the software over the years as well as probably into this tender, so ... expect it (working, open source) to happen without external assistance.

Actually, you don't even need any specs to be published to make things work: https://github.com/martinpaljak/esteidhacker/wiki/NFC

**Comment by metsma** [comment]
OpenSC master now supports new cards
