### ISSUE TITLE
Reliable crashes when removing yubikey in firefox, even with extension disabled

### ISSUE THREAD

**Issue by m0n5t3r** [open-eid/linux-installer#46]
Not sure if this is the right place for it, but I can't find any place to report bugs in awp, and I'm a bit dismayed to find it seems to be a proprietary thing, to be honest; it definitely seems about as well made as the typical proprietary blob (see the other issue about badly broken packaging).

Latest crash: https://crash-stats.mozilla.org/report/index/8c464917-1d1a-49f1-92b5-63aca0190421

Happens all the time when using the OTP feature on the yubikey, and randomly when using U2F. I think it may be related to the amount of time it spends connected, because for OTP I need to keep the thing plugged for a few seconds.

**Comment by Jalakas** [comment]
"awp" dependency is removed now: https://github.com/open-eid/linux-installer/pull/49/files
Hope there will be 19.06 release soon: https://installer.id.ee/media/ubuntu/
