### ISSUE TITLE
error with installation script, illegal option '-' in line 6

### ISSUE THREAD

**Issue by leo82** [open-eid/linux-installer#52]
hi

when I run the install-open-eid.sh script on Ubuntu 18.04.2 LTS from the Downloads folder, the following error appears:

`$ sh install-open-eid.sh`

`install-open-eid.sh: 6: set: Illegal option -`

Please advise.

**Comment by andresh** [comment]
This did the trick for me: 

<code>sed -i.bak 's/\r$//' install-open-eid.sh</code> 

Apparently the file contains DOS newlines which is causing the problem.

**Comment by metsma** [comment]
If I use curl/wget I don't get the windows EOL

**Comment by kristelmerilain** [comment]
Closing due inactivity, reopen if needed.
