### ISSUE TITLE
Workaround for Debian Buster - Linux Installer

### ISSUE THREAD

**Issue by memoricab** [open-eid/linux-installer#53]
"Debian GNU/Linux 10 (buster)"

-- Workaround: Added bionic repository in case $distro is debian

I have replaced 
`Debian)
      make_warn "Debian is not officially supported"
      echo "### Installing possibly missing https support for APT (apt-get install apt-transport-https)"
      # Debian lacks https support for apt, by default
      sudo apt-get install apt-transport-https
      case "$codename" in
        *)
          make_fail "Debian $codename is not officially supported"
          ;;
      esac
      ;;`

to

`Debian)
      make_warn "Debian is not officially supported"
      echo "### Installing possibly missing https support for APT (apt-get install apt-transport-https)"
      # Debian lacks https support for apt, by default
      sudo apt-get install apt-transport-https
      add_repository bionic
	;;`

Worked fine

**Comment by metsma** [comment]
Can you create pull request

**Comment by metsma** [comment]
Fixed by #55
