### ISSUE TITLE
open-eid causes user login to hang

### ISSUE THREAD

**Issue by jaakristioja** [open-eid/linux-installer#59]
Upon updating to the latest version of open-eid on Ubuntu 18.04.3, when the user logs in the login process hangs for about **5 minutes**!!

Looking at the running processes during login revealed that the culprit is `/usr/bin/esteid-update-nssdb` which is run during login and executes a `find /usr -name onepin-opensc-pkcs11.so` which takes way long to run, blocking the login process without any notice to the user.

Maybe its just the slow HDD on that old laptop, and a huge `/usr`, but running `find` like this is nevertheless not acceptable. Please fix!

The change causing this seems to have been introduced by commit d9dee84a3e4b2ecd422e73519f2097b96d56131d.

**Comment by jurta** [comment]
This makes Linux unresponsive, need to revert to old version.

**Comment by jaakristioja** [comment]
@metsma, @kristelmerilain: Was this already fixed by 0150f8f9199a52a9e677b92d11858c44f23fa75a?

**Comment by kristelmerilain** [comment]
Yes.
