### ISSUE TITLE
Linux installation of token signing requires ld but it's not a dependency

### ISSUE THREAD

**Issue by TaaviE** [open-eid/linux-installer#64]
In the script `/usr/bin/esteid-update-nssdb` at line 29 the installation script fails with the error `ld: command not found`, I solved it by installing `gcc-8` manually, but if it's required like that to enable ID-card functionality in Chrome(/ium) then it should be the package's dependency.

https://github.com/open-eid/chrome-token-signing/issues/138#issuecomment-595095092

**Comment by kristelmerilain** [comment]
#60
