### ISSUE TITLE
Outdated download links on id.ee

### ISSUE THREAD

**Issue by gunnarrentzsch** [open-eid/linux-installer#73]
I noticed that the Linux download links on https://www.id.ee/en/article/install-id-software/ are outdated. I suggest linking to Github directly. I would assume that users who are able to install using an .sh script are able to download from Github. With outdated links on the official page there is a risk of users not being aware of newly supported distributions/ Ubuntu flavors.

**Comment by Counter178** [comment]
Though the idea is good, the only risk here is the new distribution support.
Some development cases need more spare time and are linked to either OpenSC project, Web browser, or even a third party policy changes.
Thus the download links are updated when official release has been confirmed & done to avoid problems.
