### ISSUE TITLE
apt-key is deprecated

### ISSUE THREAD

**Issue by notpushkin** [open-eid/linux-installer#83]
> `apt-key add [filename]`
> 
> Note: Instead of using this command a keyring should be placed directly in the /etc/apt/trusted.gpg.d/ directory
> with a descriptive name and either "gpg" or "asc" as file extension.\
> &nbsp;&nbsp;&nbsp;&nbsp;— **[apt-key(8)] manpage**

[apt-key(8)]: http://manpages.ubuntu.com/manpages/bionic/en/man8/apt-key.8.html#commands

Here's [a couple reasons](https://gist.github.com/notpushkin/1cbdd3cbab0cf3570f87b7f2c0cb852d#why) why `apt-key add` might be deprecated. I would suggest using something like this:

```sh
echo "$RIA_KEY" \
  | gpg --dearmor \
  | sudo tee /etc/apt/trusted.gpg.d/ria-repository.gpg \
  > /dev/null
```

I've noticed that a couple lines above you the script mentions that `gpg` can't be used because it “always creates files on disk”, but that shouldn't be a problem because `gpg --dearmor` doesn't touch disk at all. We could instead write ASCII-armoured key, but this [doesn't work on some systems](https://github.com/Eloston/ungoogled-chromium/issues/1071).

Would there be any other concerns? I'll be happy to send in a PR!

**Comment by metsma** [comment]
Feel free to seend PR
