### ISSUE TITLE
Publish the PGP key on id.ee domain

### ISSUE THREAD

**Issue by laur89** [open-eid/linux-installer#93]
Would it be possible to (additionally) publish the PGP key on a static URL as opposed to having it packaged inside the [installer script](https://github.com/open-eid/linux-installer/blob/master/install-open-eid.sh#L9)? It'd help users with their own automated installation logic as opposed to having to rely on the installation script published by open-eid.

Examples from other projects:
[Signal](https://updates.signal.org/desktop/apt/keys.asc)
[OpenVPN](https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub)
[Docker](https://download.docker.com/linux/debian/gpg)

**Comment by Counter178** [comment]
> Would it be possible to (additionally) publish the PGP key on a static URL as opposed to having it packaged inside the [installer script](https://github.com/open-eid/linux-installer/blob/master/install-open-eid.sh#L9)? It'd help users with their own automated installation logic as opposed to having to rely on the installation script published by open-eid.
> 
> Examples from other projects: [Signal](https://updates.signal.org/desktop/apt/keys.asc) [OpenVPN](https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub) [Docker](https://download.docker.com/linux/debian/gpg)

The previously described PGP key for users is available here: https://installer.id.ee/media/install-scripts/C6C83D68.pub 

Closing issue.
